### ISSUE TITLE
Installing "git-utils@4.1.2" failed.

### ISSUE THREAD

**Issue by AstroBoy269** [necrose99/necromancy-overlay#16]
Attempting to install git-utils for my Atom Editor on Mac/El Capitan

apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.4

Installing “git-utils@4.1.2” failed.Hide output…

> git-utils@4.1.2 install /private/var/folders/x9/g6vj4s2x6xd6cfhhxcb227540000gp/T/apm-install-dir-116125-10291-1x8hm0p/node_modules/git-utils
> node-gyp rebuild

make: **\* No rule to make target `Release/obj.target/libgit2/deps/libgit2/src/annotated_commit.o', needed by`Release/git2.a'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/x9/g6vj4s2x6xd6cfhhxcb227540000gp/T/apm-install-dir-116125-10291-1x8hm0p/node_modules/git-utils
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/lance/.atom/.apm/.apmrc" "--userconfig" "/Users/lance/.atom/.apmrc" "install" "/private/var/folders/x9/g6vj4s2x6xd6cfhhxcb227540000gp/T/d-116125-10291-1w2lb95/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! git-utils@4.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@4.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/x9/g6vj4s2x6xd6cfhhxcb227540000gp/T/apm-install-dir-116125-10291-1x8hm0p/npm-debug.log

**Comment by necrose99** [comment]
I'm not sure of OSX , Just Linux  , Gentoo and or Sabayon , and might I have the package  in question 
app-editors/atom by the look of it.
